Repository Druue/Sunny-Flowers, pull requests merged in 2021-10, with the labels that each got.

#45 No unwrap
  README.md
  src/commands.rs
  src/effects/now_playing.rs
  src/effects/queue.rs
  src/handlers.rs
  src/main.rs
  src/utils.rs
Labels: cleanup, hacktoberfest-accepted

#43 Big Refactor
  Cargo.lock
  Cargo.toml
  README.md
  src/checks.rs
  src/commands.rs
  src/effects/deafen.rs
  src/effects/join.rs
  src/effects/leave.rs
  src/effects/mod.rs
  src/effects/now_playing.rs
  src/effects/play.rs
  src/effects/queue.rs
  src/effects/skip.rs
  src/effects/stop.rs
  src/handlers.rs
  src/hooks.rs
  src/main.rs
  src/structs.rs
  src/utils.rs
Labels: cleanup

#51 Various CI improvements
  .github/workflows/docker-publish.yml
  .github/workflows/rust.yml
Labels: hacktoberfest-accepted
